Fixed tandem

diff --git a/tandem b/tandem
--- a/tandem
+++ b/tandem
@@ -20,7 +20,7 @@ FILE=$1
 
 if [[ "$FILE" == *.td ]]
 then
-  echo "valid filename"
+  : # echo "valid filename"
 else
      echo "COMPILATION FAILED - invalid filename"
      exit
@@ -28,7 +28,7 @@ fi
 
 if [ -f "$FILE" ]
 then
-    echo "the file exists"
+     : #echo "the file exists"
 else
     echo "COMPILATION FAILED - the file does not exist"
     exit
@@ -38,11 +38,11 @@ fi
 #check ant 1.8
 #check ruby 1.9.2
 
-if type -p java; then
-    echo "found java executable in PATH"
+if type -p java &>/dev/null; then
+    : #echo "found java executable in PATH"
     _java=java
-elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
-    echo "found java executable in JAVA_HOME"
+elif [[ -n "$JAVA_HOME" ]] && [[ "$JAVA_HOME/bin/java" ]];  then
+     : # echo "found java executable in JAVA_HOME"
     _java="$JAVA_HOME/bin/java"
 else
     echo "COMPILATION FAILED - no java"
@@ -51,9 +51,9 @@ fi
 
 if [[ "$_java" ]]; then
     version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
-    #echo version "$version"
+     : #echo version "$version"
     if [[ "$version" > "1.5" ]]; then
-        echo "version is more than 1.5"
+      : #  echo "version is more than 1.5"
     else
         echo "COMPILATION FAILED - version is less than 1.5"
 	exit
@@ -62,11 +62,11 @@ fi
 
 
 
-if type -p ant; then
-    echo found ant executable in PATH
+if type -p ant&>/dev/null; then
+     : #echo found ant executable in PATH
     _ant=ant
-elif [[ -x "usr/bin/env ant" ]];  then
-    echo "found ant executable in ENV_ANT"
+elif [[ "/usr/bin/env ant" ]];  then
+    : #echo "found ant executable in ENV_ANT"
     _ant="usr/bin/env ant"
 else
     echo "COMPILATION FAILED - no ant"
@@ -74,10 +74,10 @@ else
 fi
 
 if [[ "$_ant" ]]; then
-    version=$("$_ant" -v 2>&1 | awk -F ' ' '/ / {print $4}')
-    echo version "$version"
-    if [[ "$version" > "1.8.0" ]]; then
-        echo "version is more than 1.8"
+    version=$("$_ant" -version 2>&1 | grep -e "1\.8\.[0-9]")
+    : #echo version "$version"
+    if [[ "$?" == "0" ]]; then
+        : #echo "version is more than 1.8"
     else
         echo "COMPILATION FAILED - version is less than 1.8"
 	exit
@@ -89,12 +89,12 @@ fi
 JRUBY_OPTS=--1.9
 
 
-if type -p ruby; then
-    echo "found ruby executable in PATH"
+if type -p ruby &>/dev/null; then
+   : # echo "found ruby executable in PATH"
     _ruby=ruby
-elif [[ -x "usr/bin/env ruby" ]];  then
-    echo "found ruby executable in ENV"
-    _ruby="usr/bin/env ruby"
+elif [[ "/usr/bin/env ruby" ]];  then
+   : #echo "found ruby executable in ENV"
+    _ruby="/usr/bin/env ruby"
 else
     echo "COMPILATION FAILED - no ruby"
     exit
@@ -108,7 +108,7 @@ if [[ "$_ruby" ]]; then
     if [[ "$?" > "0" ]]; then
     use_jruby=1
     else
-    echo "Passed Ruby Check"
+    : #echo "Passed Ruby Check"
     fi
 fi
 
@@ -119,15 +119,38 @@ DIR=$(pwd)
 
 a=$(ruby src/dependency.rb "$FILE" | tr " " "\n")
 
+
 for x in $a
 do
-	ant walk -Dfile="$x" -q
+	walk_test "$x"
 done
 
 
 echo "compiling ..."
 
-ant walk -Dfile="$FILE" -q
+walk_test() {
+
+	ant_out=$(ant walk -Dfile="$1")
+	ant_out=$(echo $ant_out | sed 's/\(.*\)\(walk: \)//1' | sed 's/BUILD SUCCESSFUL//g' | sed 's/Total.*//g')
+	ant_out1=$ant_out
+	ant_out1=$(echo $ant_out1 | sed 's/\s+//g')
+	#echo $ant_out
+	#echo ${#ant_out}
+
+	if [[ ${#ant_out1} == "0" ]]; then
+	: #echo "GOOD"
+	else
+	echo "$ant_out"
+	echo "ERROR"
+	exit
+	fi
+
+}
+
+
+walk_test "$FILE"
+
+
 
 ruby_file=${FILE%.*}
 
